### DISCUSSION TITLE
I couldn't find a VERCEL TOKEN environment

### DISCUSSION THREAD

**Discussion by sujamess** [UnlyEd/github-action-await-vercel#42] [Q&A]
## Workflow
``` yaml
steps:
  # Waiting for Vercel deployment
  - uses: UnlyEd/github-action-await-vercel@v1.1.0
    id: await-vercel
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    with:
      deployment-url: ${{ secrets.VERCEL_DEPLOYMENT_URL }}
      timeout: 10 # Wait for 10 seconds before failing
```

## Error
``` bash
Run UnlyEd/github-action-await-vercel@v1.1.0
Error: VERCEL_TOKEN environment variable is not defined. Please create a GitHub "VERCEL_TOKEN" secret. See https://vercel.com/account/tokens
/home/runner/work/_actions/UnlyEd/github-action-await-vercel/v1.1.0/lib/main.js:38
        throw new Error(message);
        ^

Error: VERCEL_TOKEN environment variable is not defined. Please create a GitHub "VERCEL_TOKEN" secret. See https://vercel.com/account/tokens
    at runConfigChecks (/home/runner/work/_actions/UnlyEd/github-action-await-vercel/v1.1.0/lib/main.js:38:15)
    at Object.<anonymous> (/home/runner/work/_actions/UnlyEd/github-action-await-vercel/v1.1.0/lib/main.js:65:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

I already created a `VERCEL_TOKEN` secret and I also see this error on [UnlyEd/github-action-await-vercel](https://github.com/UnlyEd/github-action-await-vercel/pull/40) with a dependabot's pull requests

**Comment by Vadorequest** [comment]
Regarding the configuration of https://github.com/UnlyEd/github-action-await-vercel, a VERCEL_TOKEN is configured, though.

![image](https://user-images.githubusercontent.com/3807458/139811410-a698722f-6f16-4f85-acf2-9beb3e35ecb6.png)

Looking back at the logs of the actions, it seems that it failed to retrieve the token in the past, too. But it also worked 15 days ago...

https://github.com/UnlyEd/github-action-await-vercel/actions

![image](https://user-images.githubusercontent.com/3807458/139812147-5047aa41-7ad0-4a31-a849-73ec1c0b5b9a.png)

I'm not sure why you encountered this issue. It seems a bit random at first look. 🤔

**Comment by Vadorequest** [comment]
Okay, the reason why the VERCEL_TOKEN was empty and why the actions failed at https://github.com/UnlyEd/github-action-await-vercel/actions is because the workflow was triggered by a 3rd party, which doesn't have read access to our repository GitHub's secrets.

See https://stackoverflow.com/a/58740879/2391795 for deeper explanations.

And the reason sometimes it worked, was because those runs were triggered by our own PRs, which have read access to the GitHub's secrets.

Now, why did it fail for you is another issue, I believe you should log your VERCEL_TOKEN to see if it contains the expected value.

**Comment by Vadorequest** [comment]
I suggest trying using 1.2.14 version. And if you can provide your full action's code too, that might be helpful.

**Reply by sujamess** [reply]
I use your actions for auto-merging the dependabot pull requests. This is the full actions code.
``` yaml
name: Dependabot Auto Merge

on:
  pull_request:
  workflow_dispatch:

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-18.04
    if: |
      github.actor == 'dependabot[bot]' &&
      github.event_name == 'pull_request' &&
      startsWith(github.event.pull_request.title, 'Bump')
    steps:
      # Waiting for Vercel deployment
      - uses: UnlyEd/github-action-await-vercel@v1.1.0
        id: await-vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          deployment-url: ${{ secrets.VERCEL_DEPLOYMENT_URL }}
          timeout: 10 # Wait for 10 seconds before failing

      - name: Display deployment status
        run: "echo The deployment at ${{ fromJson(steps.await-vercel.outputs.deploymentDetails).url }} is ${{ fromJson(steps.await-vercel.outputs.deploymentDetails).readyState }}"
      
      # Auto merge dependabot
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.TOKEN }}
```
