### ISSUE TITLE
What is `nextjs-bzyss249z.vercel.app`

### ISSUE THREAD

**Issue by spences10** [UnlyEd/github-action-await-vercel#8]
Hi, I've come across this action from the depreciated wait for vercel action

I'm looking to use this as wait for vercel doesn't seem to wait for the deployed URL

I'm looking at the documentation and it's not really clear what this section is for:

```yaml
    steps:
      - name:
          Retrieve deployment URL (example on how to set an ENV var)
        run:
          'echo VERCEL_DEPLOYMENT_URL=nextjs-bzyss249z.vercel.app >>
          $GITHUB_ENV'
```

Is `nextjs-bzyss249z.vercel.app` the base URL? So if I'm doing this for Google it'd be `google.com`??

It's confusing because the url looks like a generated on, like one a build would be on before getting pushed to the production URL say, understand? 

What I'm trying to say is it looks like that url is a generated temporary url and I don't know where that would come from

This is from my current workflow and that url is generated by vercel, it looks like you want me to pass in the generated url. defeating the purpose of the workflow
![image](https://user-images.githubusercontent.com/234708/103152394-61abcd80-477f-11eb-8152-453596d940e0.png)

**Comment by Vadorequest** [comment]
Hi @spences10, yes you're right. The `nextjs-bzyss249z.vercel.app` is the base url, AKA the domain base url. It could be `hello.vercel.app`, or `google.com`.

You can use any domain url, whether it's your production url, or a dynamic one.

If I understand correctly, you were using `mskelton/wait-for-vercel-action` to resolve the dynamic url assigned to your deployment?

There might be some differences between what `UnlyEd/github-action-await-vercel` and `mskelton/wait-for-vercel-action` do that we missed?

Here is how we resolve the dynamic Vercel URL in our workflow, by reading the logs generated when running `vercel` to deploy. See https://github.com/UnlyEd/next-right-now/blob/v2-mst-aptd-at-lcz-sty/.github/workflows/deploy-vercel-staging.yml#L74

But that's probably not something you'd like to do. Could you explain your workflow and what you expect from the Action?

As a side note, you can see our discussion with mskelton at https://github.com/UnlyEd/github-action-await-vercel/discussions/3, he has no plan on removing the action from GitHub at the moment. (and if his action solves a different problem, it might be worth keeping around)

**Comment by spences10** [comment]
Hey @Vadorequest, thank for the reply, apologies I should have added my use case

It's for e2e testing with Cypress, the current tool I have used to work great but now it doesn't seem to wait so I'm always re-running the action. I'm guessing this is the case because local e2e tests pass but the action fails then when I run it again manually it passes 🙃

Here's [my current workflow], the feedback I have is that I tried this action and it didn't get past the first part:

```tml
steps:
  - name: Retrieve deployment URL (example on how to set an ENV var)
    run: "echo VERCEL_DEPLOYMENT_URL=nextjs-bzyss249z.vercel.app >> $GITHUB_ENV"
``` 

Even when I change the `nextjs-bzyss249z.vercel.app` url to mine, I have a vercel secret already on the project I'm using for `mskelton/wait-for-vercel-action` and that's it, right? I don't need any other secrets set up to run this now it should do the thing, but it's not.

Thanks again 👍

[my current workflow]: https://github.com/spences10/scottspence.com/blob/use-theme-ui/.github/workflows/ci.yml

**Comment by Vadorequest** [comment]
Alright, thanks for the explanation.

So, you run `mskelton/wait-for-vercel-action@v1.2.0` and wait for the Vercel deployment to be ready. The action returns the url of the latest Vercel deployment, it might not return the url of the deployment you actually want. While your current setup might seem to work fine, it will "fail" if you push too many commits in a short amount of time, as you'll run E2E tests against the wrong domain. (because it resolves the latest deployment, so it gets confused when there are parallel deployments)

Note that you'll need to change your current `CYPRESS_BASE_URL: ${{ steps.wait-for-vercel.outputs.url }}` by `fromJson(steps.await-vercel.outputs.deploymentDetails).url`. You have access to all those proeperties: https://github.com/UnlyEd/github-action-await-vercel/blob/main/src/types/VercelDeployment.ts

**Comment by spences10** [comment]
I run the example and it just resolves with the URL I gave it, so I'm still not sure how to use this.

Do I add the deployment URL to the `.yml` file each time? Seems a bit redundant if that's the case

**Comment by Vadorequest** [comment]
Our action doesn't have a `token` input.

Actions aren't interchangeable, you can't expect keeping the input of an existing action when switching another one, you need to read their documentation.

```yml
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Vercel
        uses: UnlyEd/github-action-await-vercel@v1.1.0
        id: await-vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          deployment-url: YOUR_URL # TODO Replace by the domain you want to test
          timeout: 90 # Wait for 90 seconds before failing
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress.io
        uses: cypress-io/github-action@v2.7.0
        env:
          CYPRESS_BASE_URL: fromJson(steps.await-vercel.outputs.deploymentDetails).url
```

But I'm not sure if that'll help with your use case, because our action works slightly differently from wait-for-vercel, and wasn't intended to support your case. In our action, the domain you want to test must be known and provided as input. That's because our action awaits for a particular domain to be deployed, while wait-for-vercel awaits the lastest deployment and therefore doesn't need to know which domain/url to await for.
